[package]
name = "sunray"
version = "0.1.0"
authors = ["guimcaballero <guim.caballero@gmail.com>"]
edition = "2018"

[lib]
name = "sunray"
path = "src/lib.rs"

[[bin]]
name = "sunny"
path = "src/main.rs"

[dependencies]
rand = "0.7"
rayon = "1.4.0"
image = "0.23.10"
